spring:
  datasource:
    username: homestay
    password: homestay
    url: jdbc:mysql://localhost:3306/homestay

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
     #mode: always